### ISSUE TITLE
Flag for xplat directory name

### ISSUE THREAD

**Issue by netwobble** [nstudio/xplat-issues#6]
Hi folks,

Is there a flag to rename directory from xplat to something such as "platforms"  To me it seams more natural.  I'm sure other developers would probably choose something else.  Having a flag will help.  Is there any dependencies on the schematics to this name for wiring up.. etc?

Cheers,
AJ

ps great work on bringing nx and nativescript together.  Please feel free to check out my repo after conversion is complete.

**Comment by NathanWalker** [comment]
Hi @netwobble , thanks for this feedback. Funny enough we started with directory named `platforms` :) Problem was for long time {N} users was confusing because each {N} app has it's own `platforms` directory containing `ios` and `android` folders.

I like the thought of a flag. It would require some special considerations in the schematic. I'll label this as feature for consideration 👍 

Thanks btw, is there a link to your repo? Would love to check it out.

**Comment by NathanWalker** [comment]
@netwobble I appreciate this suggestion - For now we will stick with `xplat` due to instances like above to keep consistent - it will also help keep the schematic simpler and future documentation with sticking to a consistent pattern.
